### PR TITLE
Remove files that are now in O2. 

### PR DESCRIPTION
**Pull request by aphecetche**
Adapt the rest to use O2 where possible.

### CODE REVIEW

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
Hi,

@brinick dberzano

I'm again confused by the PR check. Should the +test trigger something or not ?
Also, I suspect the check is not using the latest alidist, is that possible ? How can I check ?

Thanks,

**Comment by brinick** [comment]
Hi Laurent

Within the alo repo, trusted users - such as yourself - that open a PR
will automatically get testing. Regarding alidist...the build script makes a 
loop over all open PRs in the repo, testing each PR in turn.
Once every loop, the alidist repo is updated to latest master.

**Comment by aphecetche** [comment]
ok, so the +test is _not_ needed, but some patience might be ;-)  do I get it correctly ?

**Comment by brinick** [comment]
Sounds correct 😄

**Pull request merged**
