### PR TITLE
No more need for a FindO2.cmake

### PR DESCRIPTION
**Pull request by dstocco**

### CODE REVIEW

**Comment by dstocco** [comment]
Dear @MichaelLettrich and @ktf ,
this PR seems to be failing, but I cannot access the log files (the link redirects me to a non-existing webpage).
Do you know if there is a way to retrieve the logs? I tried to compile it on alidock and it is working just fine, so I have no clue why the PR is failing.
Thanks in advance,
cheers,
Diego

**Comment by ktf** [comment]
I restarted the builder which should fix the problem.

**Comment by dstocco** [comment]
Hi @ktf ,
thanks for the restart. However, I see that the rebuild was not triggered. Should I push a fake commit to trigger it or I just need to wait a little longer?
Thanks!

**Comment by ktf** [comment]
No, it just takes a bit of time.

**Comment by dstocco** [comment]
Indeed, it worked in the end.
Thanks!

**Pull request merged**
